### ISSUE TITLE
Cancelable attribute should be removed from the spec because it already referenced in Event.idl

### ISSUE THREAD

**Issue by gked** [w3c/editing#100]

**Comment by foolip** [comment]
Just noticed this, and the typo (`canceable`), ping?

**Comment by johanneswilm** [comment]
@gked I recognize this is still not entirely removed (which it should). However, currently the ui-events spec says that the event is cancelable, whereas the input-events spec says this about cancelability: "Varies: False for inputTypes insertCharacter and deleteComposedCharacter during IME composition. True otherwise"

The false in the mentioned cases was due to arguments from browser makers about it not being possible to stop the DOM modification when running in IME, as that may create problems for the IME. Is this something that you have discussed at the meeting in January and found a way to avoid (so that the beforeinput event always can be canceled)?

**Comment by gked** [comment]
@johanneswilm: From what I recall, we didn't really talk about it. The only thing we wanted to figure out was the order in which events should be fired and when compositionupdate should be fired(before or after dom update)

**Comment by johanneswilm** [comment]
@garykac @gked: Ok, could we get some clarity on this? As of current state of affairs, we need the cancelable attribute of the beforeinput event to be true almost always, with a few exceptions related to IME input. Could we get this into the UI events spec or should we keep the cancelable here as well?

**Comment by johanneswilm** [comment]
Has been resolved as of F2F Auugust 2016: UI Events spec will add this, has been removed from Input Events.
