### ISSUE TITLE
inputType should be tied to the command names and having that tied to a way of declaring what you support

### ISSUE THREAD

**Issue by gked** [w3c/editing#110]

**Comment by johanneswilm** [comment]
When you say "command names" what kind of command names? Those used in execCommand? And who should declare what they support? The webapp or the browser? Are there proposals for how this could take place?

**Comment by gked** [comment]
@johanneswilm: 
When you say "command names" what kind of command names? Those used in execCommand? - Yep, we were referring to execCommands.

And who should declare what they support? The webapp or the browser? Are there proposals for how this could take place? - We were thinking that webapps should have a way to opt-in for things that they want to support. There is nothing concrete in terms of proposals as of yet. Perhaps, we could discuss that in our next F2F?

**Comment by johanneswilm** [comment]
@gked: Ok, so we are going back to using execCommand? Will we define how the execCommand commands works?

I think the most important for webapps is to have a way to make all extra content menus go away - easily. Secopnd priority is to make just the content menus used in Safari go away (= the ones that go beyond the clipboard actions).To tie that in with defining all of execCommand may not be so helpful, as it may take decades to really fix all of execCommand, and there is some chance that it may never happen.

But if you feel you can standardize execCommand behavior and make it configurable, I don't want to discourage you from working on that. Just don't postpone the option to make all the menus go away until after you are done, because that's quite urgent to have fixed right away.

I think spending some time on finding out how to turn everything off is a good idea for the next F2F. It would be good to have proposals at that time on how to do that. Just a very simple "All execCommand commands requirering an editing host and all extra menus are turned off by default on cE=events" would be good enough for most JS editors, I think.  So if browsers don't like that idea, maybe you could come up with an alternative proposal?

Anything beyond turning everything off would be great if you can make it happen, but it's not really essential to make an editor and may end up not being used by editors who prefer implementing actions themselves and drawing their own menus.

**Comment by ojanvafai** [comment]
Having the names match the execCommand names does not require speccing execCommand itself. In the worst case, we are just careful to pick command names that happen to match the de facto standard that is the existing names.

**Comment by johanneswilm** [comment]
I am ok with that. I think we should change the names in case they diverge.

**Comment by johanneswilm** [comment]
# Which execCommand commands?

What do you guys think about these? @ojanvafai @gked @choniong 

## Useful

Looking at the execCommand names, it seems that these would be useful because there is already an established keyboard shortcut: `bold, italic, copy, cut, paste, redo, undo, underline, justify (center, right, left), superscript, subscript, delete/backspace (various), outdent`.

The following doesn't have an established keyboard shortcut, but one could imagine creating one: `strikeThrough, indent [1], insertOrderedList [2], insertUnorderedList [2], insertParagraph [3], removeFormat, insertHorizontalRule`.

These apparently have a shortcut, but the corresponding execCommand seem like they wouldn't do what the established shortcut does: `increaseFontSize, decreaseFontSize`.

## Possibly useful

Some could work if the browser provides a menu for styling, the way Safari does: `hiliteColor, foreColor, heading`.

## Not very useful

Other commands seem less helpful. I am not sure how a user would want to express these without JS defined menus: `unlink, createLink, insertImage`.

 Or whether these are things editors should generally do: `styleWithCSS, useCSS, unlink, backColor, contentReadOnly, enableInlineTableEditing, enableObjectResizing, formatBlock, insertBrOnReturn`. 

[1]  As tab key isn't normally working for this purpose in browsers.
[2]  Probably: Turn current paragraph into first item in a list.
[3] Probably: Turn the block element where the caret is into a paragraph.

**Comment by johanneswilm** [comment]
Thinking about this some more, if Safari or others want to have a menu where users can choose the font or font size, then we kind of need this. But then we also need to specify other attributes: fontsize and font name that need to be available in the beforeinput event. And if we declare what is available, we also need to be able to say what font sizes and fonts are available to choose from. Creating a new issue for this.

**Comment by johanneswilm** [comment]
The command names have been implemented. A solution for turning features off/on is being worked on in #141
