### ISSUE TITLE
copy/cut and text-transform

### ISSUE THREAD

**Issue by yosinch** [w3c/editing#178]
Can we standardize clipboard content of "copy" and "cut" command at least text-transform[1][2]? The discussion was happened on April 2015 in CSSWG but we don't have conclusion.

My proposal is
- text/plan: text applied text-transform like Element#InnerText[3]
- text/html: text is as same as Text node == no white space collapsing no text-transform.

[1] http://crbug.com/325231 text-transform should not affect clipboard text/html
[2] https://lists.w3.org/Archives/Public/www-style/2015Apr/0015.html [css-text] copying text-transform'd text
[3] https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute

**Comment by johanneswilm** [comment]
@yosinch I am not entirely sure how to read your proposal for text/html. I am personally in favor keeping the HTML structure as it is when moving it to the clipboard - so that means not turning text into capitalized text or alike. The reason for that is that only if you do not change the structure, you keep the original data intact. How this is then ending up in the final paste location is up to the paste handling script of the receiver. Some apps may want to apply the transformation, while others may not. At times the application where the paste takes places may be able to guess where the original sources come from and then act accordingly -- but that does not work if the transformation has been applied already.

And example for that could be a site that allows copying book information from a well-known bookshop site directly into a form or inside a document. The bookshop site uses all caps titles of all books for styling purposes, but when pasting the title, the application that handles the paste wants to use the original capitalization.

**Comment by johanneswilm** [comment]
Now being tracked in https://github.com/w3c/editing/issues/181
