### ISSUE TITLE
Unable to keep selecting text from one table cell to another. (contenteditable)

### ISSUE THREAD

**Issue by BoQsc** [w3c/editing#186]
Here we can see how text selection is canceling while selecting from one `contenteditable` `<td>`  to the another.
![screencast from 2018-12-08 12_18_42](https://user-images.githubusercontent.com/21064622/49684945-bcfcbb80-fae3-11e8-8988-17b5aa5c5534.gif)

Quick Example:
```
<table>
<tr><td contenteditable="true">test</td></tr>
<tr><td contenteditable="true">test</td></tr>
</table>
```
Can anyone suggest how I suppose to achieve this, so that it continue selecting on the other table cell?

**Comment by johanneswilm** [comment]
You should put both in the same contenteditable. Instead of using pure contenteditable, use one of the many editors out there. Editor frameworks will allow you to define custom filters so that you can disallow editing changes on all other parts of the table except those two cells that you really want to be editable.

Please reopen if this answer does not fulfill your requirements.
