### ISSUE TITLE
Specification status report(s) for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/editing#199]
Please can you respond to this comment with a brief Contenteditable specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by johanneswilm** [comment]
@LJWatson Progress last 12 months:
* **Input Events level 1** - has obtained more tests. Has 2 implementations. Should be ready for CR. Need feedback from W3C on next steps.
* **Input Events level 2** - same tests apply, still only has 1 implementation. Need for one more implementer to implement this or for us to decide to continue with an alternative as a replacement (such as **EditContext**).
* **Contenteditable** - The main spec has been in sleep mode since we started working on Input Events The plan has always to go back to it after finishing Input Events. **Contenteditable-disabled** was discussed at TPAC 2018 and the suggestions made there have subsequently been added. Needs feedback from implementers to see how to move forward with this. It should be relatively compatible with **EditContext** if we go for that, but it will still need some minor adjustments.
