### ISSUE TITLE
ContentEditable with UserSelect=None needs to be documented

### ISSUE THREAD

**Issue by BenjamP** [w3c/editing#20]
From Koji Ishii at Google

**Comment by BenjamP** [comment]
Insofar as you can't modify what you can't place your cursor on, it seems acceptable to treat userelect:none same as cE=false. But I'm open to other views on that.
- Olivier Forget teleclimber@gmail.com

**Comment by teleclimber** [comment]
Does anybody have use cases for setting user-select: none inside cE?

**Comment by rniwa** [comment]
I know one use case for a mail client whereby which an attachment file is represented by an icon and a text and they wanted to make it "user-select: element" (i.e. the entire element is selected at all or not at all).  I'd imagine that use cases for user-select: none are similar.

**Comment by kojiishi** [comment]
A discussion in this TF said that cE=false within cE=true/typing should treat it as an atomic block that can deleted by BACKSPACE/DELETE. So combined with the use case from @rniwa, it looks like, as Ben suggested, all the following values are equal if within cE=true/typing:
- cE=false
- user-select:none
- user-select:all
- user-select:element

and 'user-select:none' can actually be selected and deleted if within cE=true/typing. Is this correct understanding?

And, as we allow cE=true inside cE=false inside cE=true to be selectable/editable, do we want the 'user-select' to be similar? I actually hope not, but I'm open to others.

The CSS WG put the 'user-select' property deferred to CSS UI Level 4 and wish inputs from this TF. I'm not sure how much we want to discuss/define behavior of the 'user-select' outside cE=true/typing, but I think we should make a recommendation of the behavior within cE=true/typing at least.

**Comment by johanneswilm** [comment]
@frivoal Didn't the CSSWG talk about this? And come up with something?

**Comment by johanneswilm** [comment]
@frivoal You presented on this last week. Didn't the CSSWG talk about user-select? And come up with something?

**Comment by johanneswilm** [comment]
@kojiishi 

> A discussion in this TF said that cE=false within cE=true/typing should treat it as an atomic block that can deleted by BACKSPACE/DELETE. 

That is probably true, and I would suggest one does this in a standard contenteditable environment, but if we do not handle deletion of content at all in contenteditable=typing, then does it matter how it is treated?

**Comment by frivoal** [comment]
The css wg did indeed talk about user-select, as I just added it to the level 4 css-ui spec:
http://dev.w3.org/csswg/css-ui-4/#content-selection

Quick note, reacting to https://github.com/w3c/editing-explainer/issues/20#issuecomment-66184716 : user-select: element does not mean select the whole element (that's user-select:all), it means keep the selection within the element. Yes, I know that's a bad name, that's why the spec has an issue on it: http://dev.w3.org/csswg/css-ui-4/#issue-dc2ca3bf

We did not directly discuss the user-select:none / contentEditable=true combo, but for now, what the spec says is that the computed value of user-select on an editing host is always "element", so you cannot have user-select none on a contentEditable=true element. But you can have it on descendants, which may be a problem, since it's not clear what it would do. Authors should probably be free to set it any way they want on a contentEditable=false descendant of a contentEditable=true, but for editable descendants, maybe user-select should always compute to text, or maybe only the none value should be force to compute to text, leaving all and element as they are. I've flagged this as a issue in the spec: http://dev.w3.org/csswg/css-ui-4/#issue-c6afab44

**Comment by frivoal** [comment]
Raised the issue on www-style: https://lists.w3.org/Archives/Public/www-style/2015May/0278.html

**Comment by kojiishi** [comment]
@johanneswilm 

> > A discussion in this TF said that cE=false within cE=true/typing should treat it as an atomic block that can deleted by BACKSPACE/DELETE.
> 
> That is probably true, and I would suggest one does this in a standard contenteditable environment, but if we do not handle deletion of content at all in contenteditable=typing, then does it matter how it is treated?

I don't remember the conclusion, sorry not reading the spec these days, but if we concluded so for deletion, that's fine. Are we not defining any default handlers for these intents? No default handles for arrow keys too?

The original intention of this issue is that I just want the behavior clearly defined, so if the spec defines no default handlers, things should be easier.

Other possible questions are like:
- Are we also disabling all mouse selections and let JS to handle? If so, can you clarify that?
- When JS sets the selection to user-select:none, what would happen?
- When JS sets the selection to a text node, but then JS applied user-select:none, what would happen?
- When an element has user-select:none, but one of its descendants have user-select:all, what are the expected behavior?

I suspect the current behavior is very much non-interoperable. I hope we can make it interoperable at least within ce=typing elements.

**Comment by frivoal** [comment]
@kojiishi 

> When an element has user-select:none, but one of its descendants have user-select:all, what are the expected behavior?

This is (now) defined in the css-ui-4 spec: http://dev.w3.org/csswg/css-ui-4/#valdef-user-select-none

**Comment by frivoal** [comment]
@kojiishi 
As for the use case brought up by @rniwa , I do believe there was consensus way back (although it never made it to the spec as Aryeh was not longer active) that this kind of atomic behavior should be achieved on children of contentEditable=true by setting them to contentEditable=false.

For children of contentEditable=typing, I am not sure we need to take a stance, and this should probably be left to the author to determine via scripts. Using contentEditable=false on children might be ok as well, or the author could decide to use user-select:all instead.

**Comment by johanneswilm** [comment]
> I don't remember the conclusion, sorry not reading the spec these days, but if we concluded so for deletion, that's fine. Are we not defining any default handlers for these intents? No default handles for arrow keys too?
> 
> The original intention of this issue is that I just want the behavior clearly defined, so if the spec defines no default handlers, things should be easier.

@kojiishi As it is now, arrow keys and clicking in the editable area are handled and defined. There may be cases I have not thought about, but it should be better defined then what is the case currently. However, I am not opposed to removing the handling, if that makes things clearer. Any JS editor would likely need to do normalization of caret placement before inserting or deleting anything anyway.

As for the user intentions: It seems they are all captured in the beforeInput event. There is nothing there yet for arrow keys, but we can add those.

**Comment by johanneswilm** [comment]
@kojiishi caret movement has now also been turned into an intention, see https://github.com/w3c/editing-explainer/commit/c81ca2d2ff4b9d09d7db59b8db018e65ebc6ed88 .

There is nothing yet about mouse clicking intentions. I wonder a bit on how/what to write about that.

**Comment by johanneswilm** [comment]
Given that we no longer have caret movement in ContentEditableTyping, it seems like this would only apply to ContentEditableTrue, so I have changed the label accordingly. Please let me know if this is incorrect.

**Comment by kojiishi** [comment]
Allow me to confirm, so are you trying to eliminate all the cases UA sets the selection, and thus this doesn't need to be defined? I'm not sure if that strategy works. UA devs need to implement something anyway, and I think not defining leads to non-interoperable behaviour somewhere.

What about JS sets the selection? Should it select?

When tabbing, IIUC user-select affects elements' focusability. Isn't it need to be defined?

**Comment by rniwa** [comment]
I agree. This behavior needs to be defined. However, it probably needs to be spec'ed in the selection API spec, not contenteditable=typing.

**Comment by johanneswilm** [comment]
@kojiishi: It may be a misunderstanding, but one of your comments triggered me to remove all caret movement and turn them into intentions. The idea was just that nothing happens by default -- the caret is just placed in the first legal caret position within the cE=Typing element and everything beyond that will happen via JS.

The only other thing that probably needed go into contentEdtiable=Typing could be something about how a tab/mouse click is handled (an intention event or maybe use existing events).

Everything that is not about moving the caret using arrow keys, but rather general questions about how selections should work, should be defined in the selection API, I think.

Then later you made some other comments that made me think that you want caret movement back in to elements set as contentEditable=Typing. That's what ticket https://github.com/w3c/editing/issues/58 was opened for.

**Comment by kojiishi** [comment]
@johanneswilm sorry it looks like if I mislead you, but I didn't mean to indicate my preference of how caret movements should be defined. Allow me to go back there if you're ok.

IIUC, we have 3 choices:
1. UA implements all caret movements.
2. Caret movements are turned into intentions:
   1. JS can override them, but UA has default behaviors.
   2. No default behavior defined, JS handles them all.

I'm fine with any of these options. I just wanted to tell you that, if we were going to 1. or 2.i., I wish the spec clarifies what UA should implement clearly. But how much the spec should define and how much it should leave UA to decide would be a tough discussion; platform behaviors and good i18n support are two primary concerns, and doing them correctly is likely to be a hard work. It's still possible, but I suppose you'll find a lot of work in front of you, from studying needs and constraints to coordinating the discussion to a consensus among all editor devs and all UA devs.

If you're happy with the work, I'm fine with any of these options at this moment.

I agree that the caret movements, selections, and focus are tightly coupled. I'm fine where they're defined, but I wish all of them to move forward together. Without all such specs making progress and being stabilized, it's not easy to review and possibly consider implementations.

**Comment by johanneswilm** [comment]
> 2ii. No default behavior defined, JS handles them all.

Do you mean that by default the caret does not move at all (unless some JS code is defined to make it move), or that by default, the caret does whatever the caret would do on that particular platform?

>  I just wanted to tell you that, if we were going to 1. or 2.i., I wish the spec clarifies what UA should implement clearly.

@kojiishi: Ok, understood. For me, the most important part is that the movement can be overridden by JavaScript and that we have all the needed primitives to also do so, also in block direction. So if option 1 means that we can only change the caret position after it has been moved by the UA, I would prefer 2i or 2ii. 

Preferably, I think we should follow the ideas laid out in the Extensible Web Manifesto, not have the caret move at all by default and instead give JS developers access to all the primitives to do caret movement themselves in the contentEditable=typing spec. Then JS developers can try that out and hopefully create a library or two for that and then eventually create another spec for contentEditable=caret-movement or some such thing in the future based on their experiences with the library. Or they may decide that creating another spec is not needed as it turned out that every editor wants to do caret movement differently due to different requirements and that it wouldn't make sense to make it behave all the same.

However, as I understand @rniwa, he believes it is a requirement that the caret movemes by default and he wants that movement to be the default behavior of the OS/UA that the user is on. So I suggest we make a compromise so that:
- Carets move according to whatever schemes are common on their UA/OS.
- All caret movements are defined as defaults for beforeInput events, so that doing preventDefault() on a beforeInput event related to caret movement will let the JS override the default behavior entirely.
- All primitives needed to do caret movement in JS in all direction (inline as well as block) are offered through one of the spec. The most important being the actual placement of the caret.

**Comment by rniwa** [comment]
That sounds good to me. One challenge here is creating a good abstraction/API around "actual placement" of the caret such that apps written for English content doesn't get completely broken for bidirectional text or text in vertical writing mode.

**Comment by johanneswilm** [comment]
I understand the issue. My understanding is that currently it's quite broken for all of that, right? And for example Japanese is entered horizontally, left-to-right on 99.999% of all websites, correct?
I don't think we should go as far as hide information from the JS developers in order to make it impossible for them to not make their app work in non-Latin language contexts. They will likely be able to do so anyway.

What would be helpful though would be to make it easy to support other inputs than left-to-right texts. 
Editors currently need a few hundred "if else" clauses for basic operations and most likely only cover ltr horizontal text. So if most of there normal operations "just work", then it won't be much trouble at all to have a handful of of if-else clauses for rtl-text, vertical text, etc. . After all, these editors want to be used as much as possible, so it's not like they want to purposefully force non-Latin writers to switch to English or leave their editor.

Things that could make it easier: As has been pointed out, it is currently common practice to switch the selection several times during an edit operation in the JS. If I understand it right, this causes IMEs to commit partially constructed characters. If such issues can be resolved, I think it will help much more.

In the case of Fidus Writer, we became aware of the problem of character construction with Brazilian Mac OS X users, as Spanish/Portuguese/German, etc. on Mac seem to use a process similar to IME to construct characters (for example ~ + n = ñ). It wasn't that we didn't want to solve it. It was just that there were already so many issues to work around, so we didn't think it was worth adding the extra complexity needed to leave the selection after just one "~" had been typed on platforms where that may be part of a composition. 

I think it is important that this is a real compromise: The browser makers get to define their way of handling the caret and deal with bi-di, and non-Latin text directions which the JS editor creator CAN make use of. At the same time the JS editor creators are allowed to deal with the caret handling, including dealing with the different text directions, themselves.

**Comment by johanneswilm** [comment]
So in other words: I argue for given direct access to the placement info in terms of pixels, type getClientRects. If Firefox draws more than one caret, the pixel placement of both should be given. But this is in part also because I cannot think of how an abstraction could handle bi-di and vertical text automatically and still give enough information to the JS editor to make effective choices of how to move the caret.

@rniwa What type of abstraction were you thinking of?

**Comment by rniwa** [comment]
This thread has gotten way too long to discuss it in detail.

Anyhow, we really need a concrete list of use cases and requirements for selection API instead of just saying "JS editor needs more control".

**Comment by johanneswilm** [comment]
@rniwa Maybe it would be a good idea if you could explain what you mean by that more concretely, because use cases have now been offered several times relating to this question, and the information about where the caret is placed at line endings has been requested also by the MsOffice team. If the caret-placement info is solved only for line endings and none of the other cases, then surely the result will be that ltr, horizontal text editors will be easy to create right, and those with text going in other directions, will continue to be difficult, right?

I am thinking we may be talking about different things. When you are requesting use cases, how is that different from the information you have been given already? Also: Could you give us an idea of what kind of abstraction you are thinking of (no need to go into details, just to give us an idea what this is about)?

**Comment by rniwa** [comment]
@johanneswilm : Okay. Let me give you a concrete use case that necessities knowing whether the caret resides before or after a line wrap.  Suppose your editor needs to show a visual line number (i.e. wrapped lines will be treated like multiple lines) at which the caret currently resides.

One solution to address this use case is exposing whether the caret resides before or after a line wrap. If the editor can already determine where line wraps occur, such an information could help editor determine the line number.  An alternative solution is expose a mechanism to serialize a range of text including soft wraps as LF starting at some node all the way to the caret.  Such an API allows authors to count the number of lines from the first line, or from the beginning of the physical line (i.e. the first character of wrapped lines the caret is currently in).

The only reason I've picked the first solution for now is because the second API is quite expensive to implement but there could be other reasons to prefer the second API or yet another API to solve the same problem. We don't know but it doesn't matter what solution we choose as long as we allow the editor needs to compute the visual line number.

The information you've been us so far has been problems existing editors have encountered, and that unfortunately isn't really a good use case.  It's like telling your architect what problem(s) you have with your current home.  What an architect needs to know is what YOU WANT in your new home; e.g. kind of things you want to cook at your kitchen, the kind of guests you want to invite, the number of kids you want raise at your new home, etc...

Here's another observation.  Every year, hundreds of new APIs are proposed in Web Apps and other standards groups in W3C and yet all of them are initially _wrong_.  It's not that people who came up with those were incompetent.  It's that other participants often realize subtle problems with their proposals or that they have other use cases to consider.  And the key to picking the right solution is by evaluating each proposal using the list of use cases we've accumulated.  Take a look at Hixie's proposal for dependency resolution: https://lists.w3.org/Archives/Public/public-whatwg-archive/2013Aug/0277.html  He very carefully addresses each and every use case there.  Now, I think his API in that particular thread is a bit too complicated but even then we can have a constructive discussion by trimming the API surface and see which use cases can still be satisfied.  This is only possible because we have an exhaustive list of use cases.

**Comment by johanneswilm** [comment]
> An alternative solution is expose a mechanism to serialize a range of text including soft wraps as LF starting at some node all the way to the caret. Such an API allows authors to count the number of lines from the first line, or from the beginning of the physical line (i.e. the first character of wrapped lines the caret is currently in).

Yes, this is the box-tree API that is currently being worked on, as I understand it. But unless something more is added, this doesn't really say anything about where the caret is, because one range can be two different caret-positions (start or end of line). So the box tree model is a good idea, but I think it's something else than this.

> The information you've been us so far has been problems existing editors have encountered, and that unfortunately isn't really a good use case.

I understand what you are saying, but I don't think that is quite correct. Have you looked at the use cases I supplied? Or the ones Oxygen XML supplied? Most of Benjamin's editing explainer document is in large part based on Fidus Writer's needs.

Some of the other use cases that make it necessary to know where the caret is:
- An editor that wants to place the caret in the same place when the user returns to a previously saved document.
- A collaborative editor that wants to show the placement of the collaborators' carets.
- An editor that wants to implement movement in the block direction itself.

> Every year, hundreds of new APIs are proposed in Web Apps and other standards groups in W3C and yet all of them are initially wrong.

Sure, but in order to get it right, we should probably to continue to discuss based on the already given facts, and not restart the discussion from zero again.

**Comment by rniwa** [comment]
> - An editor that wants to place the caret in the same place when the user returns to a previously saved document.
> - A collaborative editor that wants to show the placement of the collaborators' carets.

These are good use cases.

> - An editor that wants to implement movement in the block direction itself.

This is not.  This is _what_ an app wants to do.  A use case is _why_ it wants to do it.

> Sure, but in order to get it right, we should probably to continue to discuss based on the already given facts, and not restart the discussion from zero again.

That's just not how we design/standardize new APIs.  You're free to propose whatever you want but you won't persuade browser vendor to implement them with an argument like that.

**Comment by johanneswilm** [comment]
> > - An editor that wants to place the caret in the same place when the user returns to a previously saved document.
> > - A collaborative editor that wants to show the placement of the collaborators' carets.
> 
> These are good use cases.
> 
> > - An editor that wants to implement movement in the block direction itself.
> 
> This is not.  This is _what_ an app wants to do.  A use case is _why_ it wants to do it.

Ok, well this is a use case for why one needs to know the position of the caret. If I understand you right, you want to go one step beyond that and ask: "Is there really any reason for why the editor needs to be able to move the caret in the block direction?" correct? 

Some use  have been mentioned in other threads already (see below link). Some more:
- To create a "tracked changes" system where the caret should move into certain parts and avoid other parts. The caret should navigate around areas that have been deleted.
- Within an editor, there may be parts that are only editable once the users enters into them with the caret. In the case of Fidus Writer we have latex formulas that are usually shown as rendered formulas in the editor using mathjax, but once the user moves the care t there, it should turn into an input field in which the user can enter the formula. And the caret should be placed where it should have been usually. Imagine this:

```
<div contentEditable="typing">
<p>This is a normal |text line</p>
<p>This line contains a <span class="formula"><svg ...></span>.</p>
<p>This is the line after the line with the formula</p>
</div>
```

| = caret
If the user hits the down arrow, it should turn into this:

```
<div contentEditable="typing">
<p>This is a normal text line</p>
<p>This line contains a <span class="formula open">X^2=3y*6|5K</span>.</p>
<p>This is the line after the line with the formula</p>
</div>
```
- To have consistent behavior of caret movement across browsers, especially if browsers each will implement caret movement differently. Imagine a class of 90 year old IT first timers. Half come with Macbooks, some with Chromebooks and some with computers locked down to only be able to use Internet Explorer on Windows 7. The teacher tells them "click in the first line after the tenth letter, then hit the arrow down" and all of the browsers do different things because the editor developers had no way to standardize behavior.
- To have custom caret movement that matches the personal preferences of the editor develoeprs. Take for example this one:

```
<div contentEditable="typing">
<p>hello |mellow</p>
<figure>
  <img ...>
  <figcaption>A nice figure</figcaption>
</figure>
</div>
<p>A sentence after the figure</p>
```

| = caret.

If the user moves the caret down, one could imagine several different things happening, some of which are:
1. The caret moves into the figcaption just below where it was previously.
2. The caret moves before the figure.
3. The caret moves after the figure.
4. The caret moves into the paragraph after the figure.

All of these seem like valid ideas, and depending on what kind of text we are editing and what the preferences of the end users and editor developers are, any of these (and probably many others) could be possible and valid editor behaviors.

> > Sure, but in order to get it right, we should probably to continue to discuss based on the already given facts, and not restart the discussion from zero again.
> 
> That's just not how we design/standardize new APIs.  You're free to propose whatever you want but you won't persuade browser vendor to implement them with an argument like that.

I think you must be referring to something else. I was referring to the fact that we now mentioned these same use cases several times already and we shouldn't just forget about that and start from zero every few days. See here for example: https://github.com/w3c/editing/issues/56#issuecomment-108086579

There are some more use cases there.

**Comment by johanneswilm** [comment]
As caret movement is handled entirely in JS, this ticket is no longer relevant.
