### ISSUE TITLE
Security Review

### ISSUE THREAD

**Issue by noncombatant** [w3c/editing#315]
I'm from Chrome Security, taking a look at the explainer.md. Here are some thoughts.

## API Affordances

The API should not require the caller to proactively do the right thing — just as people forget to proactively check the sending `event.origin` in `postMessage`, they're going to forget to explicitly mark unsanitized formats as such. This code snippet from the explainer shows the problem:

```
// This format 'text/custom' is not sanitized by the Clipboard API. It will be
// pickled if the format is specified in the {unsanitized: []} formats list.
const customText = new Blob(
  ['<custom_markup>pickled_text</custom_markup>'], {type: 'text/custom'});

// Clipboard format ordering: Pickled formats will be written before sanitized
// formats by the browser, since they're more "custom" and likely more targeted
// towards this use case.
const clipboardItem = new ClipboardItem({
  'text/plain': text,       /* Sanitized format. */
  'text/custom': customText /* Pickled format. This new format will be accepted
                            and written without rejection, as long as the new
                            unsanitized list contains this format. */
}, 
// → PEOPLE WILL FORGET THIS:
{unsanitized: ['text/custom']} /* This new list specifies the pickled format
                          'text/custom'. */
);
navigator.clipboard.write([clipboard_item]);
```

I propose instead that the specification should say that implementations MUST pickle any clipboard contents that they don't already sanitize. (And then you can remove the `unsanitized` field from the `ClipboardItem` constructor.)

### Callers Are Malicious

A key reason for this is that the reader of clipboard contents must assume the writer is malicious. A malicious clipboard writer will intentionally not mark their attack payload as `unsanitized`.

I see that you have considered this ("Alternative Considered: unsanitized if not supported by the Async Clipboard API"), but I don't understand the argument against it. I don't see that it is equivalent to the `unsanitized: true` design alternative: it *would* be possible to distinguish sanitized from unsanitized clipboard contents, because we all know in advance what the sanitized MIME formats are. (Right?)

In any case, this feature simply must ensure that clipboard readers have to opt in to reading potentially dangerous clipboard contents. We cannot trust callers to get it right.

### Explicitness Is Good

By contrast, it is good that a caller of `read` has to explicitly ask for unsanitized clipboard contents. I.e. keep this:

```
// Pickling read example. ClipboardItems returned by clipboard.read() may 
// contain pickled formats.
const clipboardItems = await navigator.clipboard.read(
    {unsanitized: ['text/custom']} /* This new list specifies the pickled format
                              'text/custom' for all read ClipboardItems. */
  );
```

## Existing OS And Application Expectations

There's a very real problem that mainstream OSs will eagerly deserialize *and execute* COM/NSObject/other objects they find and can recognize in the clipboard, leading to a severe risk of exploitation of existing software that doesn't know it's receiving input from the wacky and wild internet. (See e.g. [Compromised renderers can set arbitrary clipboard formats](https://bugs.chromium.org/p/chromium/issues/detail?id=352395). This feature essentially opens up an attack path to all web origins that was previously only open to those who had already compromised the renderer process.)

Therefore, the specification must be super clear on what format the pickled stuff will be in, and ensure that the pickling format itself is not hard to parse (thus creating *new* bugs and vulnerabilities). And that format must not be something that existing software will eagerly decode and deserialize — it should be simple, yet opaque to existing software.

### Opting In To Trouble Is Not Sufficient

Under the "Risks" section, no mention is made of the fact that the unsanitized pickled data is still very likely to be unsafe for existing implementations that were not designed and implemented for the internet threat model. It is likely to happen that native app developers will opt in to receiving unsanitized formats, and then feed them directly to their existing implementations. The specification must warn developers that they should only feed these unsanitized inputs to implementations that are hardened against internet garbage. (The *minimum* standard is intense fuzzing, such as provided by [OSSFuzz](https://google.github.io/oss-fuzz/).)

### PII

The PII issue is a concern, but probably not the biggest. It should get a dedicated paragraph. The paragraph it's in starts with an unrelated topic sentence ("This feature introduces custom clipboard formats with unsanitized content that will be exposed to both native apps and websites.").

### Why Pickling

From the perspective of an application developer, all this pickling business may seem like an extra hoop to jump through with no clear reason. The explainer should clearly link the "whole new world of attacks" discussion with the opt-in-un-pickle requirement and with the requirement that developers harden their native implementations against internet malice. (The user gesture requirement, discussed below, is not a real defense against the whole new world of attacks, and should not appear in the same paragraph.)

### User Gesture Requirement

The utility and meaning of the user gesture gate/mitigation may have been lost. As written in the explainer, I don't see that it protects much, and from the perspective of a developer might just seem like more security theater.

If (and only if) we require that the clipboard write (and possibly read) operations can only be called from within an event handler handling a `trusted` `event` (i.e. an `event` attested by the browser to have come from a true human-generated UI gesture event), can we interpret the event as indicating a person's intent. That would help us get some confidence that the write (or read) operation is not happening unilaterally, at the request of a potentially malicious web origin.

I don't think the [transient activation](https://html.spec.whatwg.org/multipage/interaction.html#transient-activation) mechanism suffices to indicate a person's intent.

But as written, that requirement and marginal benefit is not clearly spelled out in the explainer. (Developers will not click on the extended privacy-security doc.)

### No Permission

I can imagine being OK with this, for the reasons you give (comprehensibility, fatigue), in a later review after these other issues are hammered out.

## Minor Nits

Nits: Use "HTML" consistently throughout, not "html". Document could use some copy editing.

**Comment by snianu** [comment]
> I propose instead that the specification should say that implementations MUST pickle any clipboard contents that they don't already sanitize. (And then you can remove the unsanitized field from the ClipboardItem constructor.)

If the web authors don't provide the MIME type to be pickled in the `ClipboardItemOptions`, then the formats wouldn't be inserted into the clipboard as unsanitized. If the MIME type is a standard format such as `text/html`, `text/plain` etc, then only the sanitized payload would be inserted into the clipboard. If the web authors provide a custom format (`text/custom` in the example) but "forget" to provide that custom format in `ClipboardItemOptions`, then we will throw a JS exception `Type text/custom not supported on write.`

> I don't see that it is equivalent to the unsanitized: true design alternative: it would be possible to distinguish sanitized from unsanitized clipboard contents, because we all know in advance what the sanitized MIME formats are. (Right?)

The sanitized MIME formats are known, but we aren't sure when the web authors also want an unsanitized version of it. For pickled formats, it is easy to detect, but for standard formats we basically have to read/write unpickled & pickled formats even if web authors only requested for the unpickled version in their sites. With `ClipboardItemOptions` the web authors have to explicitly specify the MIME type during read/write if they want the pickled version of the MIME types in the clipboard.

For the user gesture requirement, I agree with the concerns raised regarding user intent. We have a separate issue to discuss this to make it more explicit: https://github.com/w3c/clipboard-apis/issues/52

**Comment by snianu** [comment]
Also cc'ing @BoCupp-Microsoft @dway123 @mkruisselbrink

**Comment by dway123** [comment]
> I propose instead that the specification should say that implementations MUST pickle any clipboard contents that they don't already sanitize. (And then you can remove the unsanitized field from the ClipboardItem constructor.)

Building on this, requiring sites to provide the unsanitized list allows sites to support both a unsanitized (for reading by the site) and sanitized (for reading by other sites/native apps) version of the same payload, in case a site requires information removed by sanitization. Therefore, writing unsanitized data by default (rather than via the unsanitized list) would also make addition of sanitized payloads by browser implementations be web-incompatible, as previously unsanitized content would become sanitized, potentially wiping metadata a site relies on.

> Existing OS And Application Expectations

This API is not compatible with existing native apps / software, so this should partially bypass the issue. That said, @snianu  please clarify in the explainer potential danger of unsanitized, web-originated content, and recommended defense (ex. Fuzzing), to protect from native apps simply adding pickling support and associated malicious content from the web without reconsidering their security model. It seems we could use additional discussion around potential dangers/defense in general (though explainers are intended to be brief, so I'm not sure if this may be better suited to a design document instead... either way)

**Comment by dway123** [comment]
> We have a separate issue to discuss this to make it more explicit: w3c/clipboard-apis#52

The separate issue you linked discusses a user gesture requirement for the Clipboard API overall. I suspect that Chrome Security may prefer for all new clipboard API surface to require user gesture, but that we unfortunately may not be able to add the user gesture requirement for existing API surface without a separate launch/effort, as this change is web-incompatible (may break existing sites, without a corresponding replacement to get the same functionality). Therefore, I think it's still worth having pickling require user gesture, but not the underlying Clipboard API in the meantime.

**Comment by quidity** [comment]
Continuing this for Chrome:

Looking over this issue I see a couple of areas that might be addressed but... the set of documents is quite sprawly. Feel free to point to answers that I have missed!

1) "And that format must not be something that existing software will eagerly decode and deserialize — it should be simple, yet opaque to existing software." - is this format documented, why do we think existing system apps won't try to parse it?

2) How is Chrome making sure that unsanitized data doesn't get to system apps? (i.e. how is Chrome going to write the clipboard data on Windows, on other platforms?)

**Comment by snianu** [comment]
@quidity 

> is this format documented, why do we think existing system apps won't try to parse it?

The JSON map(`Web Custom Format Map` on Windows) that tracks the mapping of the `web custom format` to its corresponding MIME type is described [here](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#os-interaction-format-naming). It only gives you the native format that you can then use to query the native clipboard and get access to the content, but it doesn't tell you what the actual content is -- It could be in a binary format, raw characters or something that only the reader-writer of the format know how to parse it in their site/native app.

> How is Chrome making sure that unsanitized data doesn't get to system apps? (i.e. how is Chrome going to write the clipboard data on Windows, on other platforms?)

The formats that are written without any sanitization to the clipboard, are custom defined by the web author/native app developer. It is not the [system defined formats](https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats) that any native apps on Windows have access to. The native app or the site needs to know the custom format name and how to parse the content of the format, in order to make sense of it. e.g. an HTML format has a standard format `CF_HTML` defined in the system clipboard format. If this type is available on the clipboard, then native apps can read it and parse the content as described [here](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa767917(v=vs.85)#overview-of-cf_html). But the custom format (that has the unsanitized payload of the HTML format) is not defined by the system, so the consumer wouldn't know how to parse the content of the custom HTML format -- the HTML content could be a full HTML document or a fragment or just the DOM element that the producer/consumer is interested in.

**Comment by quidity** [comment]
Sounds good - thanks.
