### ISSUE TITLE
contenteditabledisabled is extending `ElementContentEditable` in a wrong way

### ISSUE THREAD

**Issue by saschanaz** [w3c/editing#332]
[ElementContentEditable](https://html.spec.whatwg.org/multipage/interaction.html#elementcontenteditable) is an existing mixin, but the spec somehow is [redefining it as an interface](https://w3c.github.io/editing/docs/contentEditableDisabled/#element-contenteditable-mixin).

This is wrong and it should be `partial interface mixin` instead, as noted in https://github.com/w3c/editing/pull/265#discussion_r476025740.

**Comment by johanneswilm** [comment]
@saschanaz I agree. I think this must have been an oversight. I had initially used `partial interface ElementContentEditable` and that was changed to `interface ElementContentEditable` with the latest overhaul of the document, but it really should be `partial interface mixin` as you are saying as it is expanding upon the already existing `interface mixin`. 

Also, it should likely use `DOMCommandTokenList` rather than `DOMTokenList` as we need it extended with the "supported" attribute AFAICT. 

Do you want to make a PR or should I?
