### ISSUE TITLE
Call for demos (TPAC 2021)

### ISSUE THREAD

**Issue by travisleithead** [w3c/editing#336]
Repeating here for WG discussion.

> As in [previous years](https://www.w3.org/2020/10/TPAC/group-updates.html#intro), as part of TPAC, Marie-Claire Forgue and I are
calling for W3C groups to produce short videos to share updates from
your group's work and/or technical demos illustrating the latest
developments in your groups that would benefit from being shared with
the broader W3C community. These videos can also serve as background
material for some of the TPAC breakouts and group meetings.
>
> If someone in your group is willing to record such a video, please
contact us with the name of the volunteer by September 15 (sooner is
better); for demos, we will also want a proposed title of the demo and
ideally a description of what the demo will be about. We would then
expect to receive the recorded videos by September 27th for publication
after post-processing around October 1st.
> 
> Based on the experience from last year, we've built a collection of best
practices to help build impactful videos (esp. demos):
>
> https://www.w3.org/wiki/TPAC2021/Demos_and_Group_updates#Best_Practices_for_Recording_Videos

**Comment by johanneswilm** [comment]
How about a little demo video with two videos who are trying to chat: One on a computer, the second on a mobile phone. Black and white. All non-descript hardware items. The chat application eats their texts multiple times when they try to do IME or something else. The person with the mobile phone throws the phone in the trash, the person with the desktop computer throws the keyboard in the direction of the wall. It's all filmed in black and white.

Then there is a voice "Has it ever happened to you that you wrote some really important text only for your web browser to eat it all up so that you had to type everything again? The Web Editing Working Group is working on a number fo specifications to make such occurrences a thing of the past."  

Then color comes on. And then we present a few of our specs that relate to various issues on various devices (maybe 30 second to 1 minute) and you can see those two characters chatting while smiling.

It's meant to be absurd and funny at the same time and hopefully there won't be too many other WG with similar videos.

**Comment by travisleithead** [comment]
WG discussion: sounds fun! Happy to see @johanneswilm put that together. Follow-up with @BoCupp-Microsoft offline to see if there are specific demos for virtual-keyboard or edit-context.
