### ISSUE TITLE
application/web

### ISSUE THREAD

**Issue by martinthomson** [w3c/editing#387]
https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#os-interaction-format-naming appears to define a new media type.  Has this been [defined](https://datatracker.ietf.org/doc/html/rfc6838)?

**Comment by snianu** [comment]
These are platform clipboard formats and are not accessible to web authors. It is used by the native apps to read the custom format map JSON defined in https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#os-interaction-format-naming

**Comment by martinthomson** [comment]
Why would that matter?

**Comment by snianu** [comment]
It matters because the custom format map isn't a MIME type. It's a native clipboard format(like the [standard clipboard formats](https://docs.microsoft.com/en-us/windows/win32/dataxchg/standard-clipboard-formats)) that is used to share data across apps within the system. On Windows, the format is basically an atom defined in the [atom table](https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-atom-tables). The memory is managed by the OS.

**Comment by snianu** [comment]
Closing this issue per [this ](https://github.com/w3c/editing/issues/387#issuecomment-1022933834)comment.
