### ISSUE TITLE
define relation to HTML Editing APIs

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#48]
The HTML Editing APIs ( https://dvcs.w3.org/hg/editing/raw-file/tip/editing.html ) already started spec'ing execCommand and other relevant behavior. How does this relate to our work here?

It defines execCommand as being related to an "editing host" -- which seems to go against some of the ideas presented here.

**Comment by johanneswilm** [comment]
@fredck Have you looked at this?

**Comment by fredck** [comment]
I see those specs as a separate part of the API browsers are supposed to provide for the scope of editing. 

The "HTML Editing APIs" idea seems to be bringing to specs the API we had on browsers for more than 10 years, without much changes or innovation.  Still it is a very important work, because it aims to standardize the behavior of such API, including heuristics for several tricky cases to be faced during its implementation. This is important for those who care about that API.

The work we've been doing here so far instead is all about those who don't care about that API. Well... maybe except for Selection, which IMHO should deserve its own spec and should not be limited to "editing hosts" (after all one can have selections in normal pages as well).

I would not mix the efforts. cE should be an independent spec. If should be kept small and simple, so it will be ready at some point. execCommand and its siblings should be spec'ed independently. My advice is that, if you'll enter in the endeavour of taking those specs over, it'll severely delay the cE developments. Only if you think about taking it under the wings of this group but not working on it in the near future until cE is ready.

Then in any case, ofc, both specs must be aligned, to (1) be sure that one is not entering on the field of the other one and (2) ensure that both play well together.

**Comment by johanneswilm** [comment]
I certainly don't want to take on a spec to work on in my free time by myself forever. And I agree that the above specification is a lot about describing already available behavior.  

But I am slightly less sure about the division: When you say "cE should be an independent spec" -- you mean the "contenteditable=typing" specification that we are working on here, right? In the CSSWG F2F meeting, the above linked specification was referred to as the "contenteditable spec" just yesterday. This is somewhat confusing and it should be made clear what is what.

As for execCommand: I understand there are two different ideas about how to use it here. Whether or not it should need an editing host seems to be a decision that needs to be taken by the relevant working group at some point of time, and then all the documents should be in agreement about how they treat it. It makes no sense for us to treat execCommand as something that works in one way, when another specification claims it works differently.

It seems to me that what is needed now is that both the cE=typing and the above linked spec are put into shape and that we have a meeting of some kind that is able to reach decisions (by vote if necessary) on the parts where there is disagreement. A specification can continue to evolve over a long period of time, so we don't need to put a final stamp on the above linked spec, but if we reach clarity on some fundamental issues and edit the draft specification accordingly, we will have much less confusion.

So it seems to me that we should A) ensure that the above specification has an active editor for the time being who is able to do at least minor but fundamental changes to it, B) Preferably have all the editing specs in the same task force/working group, C) Continue to edit the specs and collect divergent ideas here on github, the mailing list, etc. D) Have a meeting (F2F or over phone) in which we can make decisions on all the issues where there are controversies.

That way, I think, we should quickly be able to get to a state where the cE=typing spec draft has reached a level where it begins to be something one can refer to confidently.

**Comment by fredck** [comment]
> But I am slightly less sure about the division: When you say "cE should be an independent spec" -- you mean the "contenteditable=typing" specification that we are working on here, right? In the CSSWG F2F meeting, the above linked specification was referred to as the "contenteditable spec" just yesterday. This is somewhat confusing and it should be made clear what is what.

IMHO, the "Editing Task Force" should centralize everything around editing. At a first stage, it would be translated into the following tree of specs:
- Editing
  - ContentEditable
    - cE=true
    - cE=typing
  - Editing Commands (execCommand & co.)

There are also other specs that are very related to editing but not exclusive to it:
- Selection (should it be inside Editing as well???)
- Ranges
- Clipboard

I assume that there will not be much love for cE=true and Editing Commands for now, but the other specs are the hot topics we should be focused at the current stage.

**Comment by johanneswilm** [comment]
> I assume that there will not be much love for cE=true and Editing Commands for now, but the other specs are the hot topics we should be focused at the current stage.

Probably true for a lot, but not everyone. For example, the CSSWG just started working on a new white space wrapping value that, among other things, is supposed to remove the hacks currently used when adding multiple spaces int he end of an element inside of cotnenteditable=true. See http://logs.csswg.org/irc.w3.org/css/2015-05-18/#e553591 (it says multi line textfields, but contenteditable was mentioned in the discussion).

So I agree, I think we should keep all of those specs here, If some are developed faster than others, that's fine. But we need to be able to make them be in sync. As for voting and final decisions, I am not entirely familiar with the process yet, but from what I hear, this has to be done in the working group itself.

**Comment by johanneswilm** [comment]
Ok, now that we have imported everything to this task force, we can close this.
