### ISSUE TITLE
What to do with execCommand?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#53]
Currently the proposals we have are:
1. Spec it and have it only work within an editing host (as now).
2. Spec it and have it work independently of editing hosts.
3. Spec it, but under a different name, and make it work only within an editing host.
4. Spec it, but under a different name, and make it work independently of editing hosts.
5. Spec only those parts that are already inter-operable, remove the rest.
6. Deprecate it and don't spec it.
7. Deprecate it and spec it.

**Comment by fredck** [comment]
When it comes to advanced browser based editing solutions like CKEditor, execCommand is irrelevant. It is not used at all. So I assume that developers of such solutions have zero interest on spec'ing it (option 6). That's in fact my **personal** vote.

There may be others instead which could be interested on such API though for cheap editing implementations.  I'm appositely not taking them in consideration in my personal vote because I want it to represent a group with specific needs, but it would be wonderful to have them leaving their voice here.

**Comment by ghost** [comment]
6 seems fine.

Even if implemented consistently across browsers, execCommand will not suffice for anything beyond simple ‘bold/italic’. What’s worse, execCommand is by definition too abstract and, used alongside more complex markup, will inevitably become dangerous (`<span style="font-weight: normal; color: black">`, anyone?)

**Comment by johanneswilm** [comment]
Agreed. I propose that at the F2F meeting in Paris, we go for 6 (deprecate it; don't spec it).

**Comment by johanneswilm** [comment]
We went for something a la "We will not spend much time on writing the spec, the browsers do not respect the spec, we keep the notice at the top, but it will likely stay around for another 100 years and will be specced some time in the future."
