### ISSUE TITLE
Can we use textnodes, and block/inline nodes as shadow roots for transparent IME handling?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#57]
Do we know if it is actually possible that block- inline and text nodes serve as shadow roots the way we imagine here?

**Comment by rniwa** [comment]
No, we can't make text nodes have its own shadow root. We need to have an element for that. I think what we need is some sort of an insertion point element.

**Comment by johanneswilm** [comment]
@rniwa that's not what all browser people seem to say:

@kojiishi: https://github.com/w3c/editing-explainer/issues/34#issuecomment-69931633

> The placeholder route can be further adjusted to make the text node as a shadow host. Currently Blink does not support creating shadow roots against text node, but this could be extended, or we could create similar mechanism without directly using shadow DOM as is.

**Comment by rniwa** [comment]
@johanneswilm : We would be opposed to supporting shadow roots on text nodes.  Supporting a feature like that will dramatically increase the complexity and the implementation cost of shadow DOM or whatever alternative name we give it to this feature.

**Comment by johanneswilm** [comment]
@rniwa Ok, well then you can come up with some other solution for Safari that has the same effect, I am sure.we can change the wording so it doesn't exlicitly call for "shadow root" if some more generic wording works better for you.

**Comment by rniwa** [comment]
The problem isn't so much how it's called but rather that what's been proposed here can't be implemented.

**Comment by johanneswilm** [comment]
You just said it will be complex. Now you say it's **impossible**? No-one forces you to do anything. But if we just continue with the same old same old broken stuff, we won't get anywhere.

**Comment by rniwa** [comment]
The alternative to not implementing shadow-root-on-text-node isn't not doing anything.  I'm suggesting to have an element to indicate where such a shadow root will reside.  What's the problem with that approach?

**Comment by johanneswilm** [comment]
As I understand it, you would insert an element into the DOM, right? That's kind of what this is trying to avoid as it will mess with various other things -- collaborative editing being one. An obvious alternative for Safari is that you can just show a small window into which people can type their IME. As I understand it, that's what many native Windows apps do anyway.

**Comment by rniwa** [comment]
No, I'm saying that the web apps will place this special element at whereever it pleases to and the the user types text into it.  The browser will then insert text into the special element and issues some intent to convert that to a regular text node later.

By the way, showing a small window to let user type in IME only happens when the app doesn't natively support IME in Windows so that's not really an option even in Windows.

**Comment by johanneswilm** [comment]
Ok, so the special element would not be part of the DOM? If so, I think that would be a good solution. Could we find a way to word it so that Chrome and Safari both can implement it in whatever way works for you?

I spoke some with a Japanese developer friend and he said he typed into a small window when not using a browser -- but now that I think of it, he is using Mac OS X.

**Comment by rniwa** [comment]
I don't think it's a thing on Mac either (I use both Windows and Mac and I'm a native Japanese speaker).

Anyway, the idea is that we'll have a special self-closing element, let's call it "caret" for now, that has a shadow DOM. A web app uses this element by inserting into at where the app wants the user to type in.  e.g. &lt;b&gt;&lt;caret/&gt;&lt;/b&gt; will let the user type a boldened text and when the browser moves the caret, blurs the focus, etc...  it'll send some event, e.g. input event, to the app with the materialized text to insert it into the "real" DOM.

WDYT?

**Comment by johanneswilm** [comment]
> I don't think it's a thing on Mac either (I use both Windows and Mac and I'm a native Japanese speaker).

If you want to, I can put the two of you in touch. Not sure what kind of apps he is using.

> Anyway, the idea is that we'll have a special self-closing element, let's call it "caret" for now, that has a shadow DOM. A web app uses this element by inserting into at where the app wants the user to type in. e.g. <b><caret/></b> will let the user type a boldened text and when the browser moves the caret, blurs the focus, etc... it'll send some event, e.g. input event, to the app with the materialized text to insert it into the "real" DOM.

Please remember I'm on the JavaScript side of things so I don't entirely understand what's going on in the browser. Do I understand correctly that you propose to just insert ONE element into the DOM at composition start, and then everything will happen in the shadow DOM until the IME is finished, at which stage its "output" is handed over to the app through an intention event (and the caret element is removed again)?

If that is correct understood, what happens if you are typing in the middle of a text node such as:
'....'<caret/>'.....' ? It will simply split the text node? What's the advantage to invoking the Shadow DOM in this case?

**Comment by rniwa** [comment]
Well, in my proposal, the app will have to split the text node and insert the caret element there.  In fact, I'm envisioning that all text insertion happens inside the caret element first and then gets inserted into the real DOM by the app itself.

The advantage of this approach is that it hides the IME interactions from the app, which is notoriously had to get right on all the platforms.

**Comment by johanneswilm** [comment]
Ok, I see. So basically it would:
1. Split text node
2. Insert caret element
3. Insert characters via whatever mechanism into shadow DOM of caret element
4. remove caret element, merge text nodes back together
5. Fire an intention event that the user wants to insert one or several characters into the place where the caret element was.
6. Event is handled by JS (which likely inserts the characters as proposed).

Right now at least, that sounds like not a bad idea to me.

Some possible issues of the top of my head:
1. What happens if the user wants to type in a place where there was no text node before? Will the text node first be inserted at 6? So if at 6 the JS decides not to insert it, there won't be any text node either afterward?
2. What happens if the user types at the start of a text node that has a previous sibling text node but the JS decides not to insert the characters anyway. Will the previous sibling text nodes now suddenly be joined together (under 4)?
3. What happens if one wants to make a snapshot of the current HTML and save that to disc or send to another collaborative user while the user is typing? I guess it will contain the <canvas/>-element, right? One can of course filter that out, but can one know whether or not to the two text nodes on either side should be merged together or not?

**Comment by rniwa** [comment]
My proposal would be that the browser doesn't do anything with the text node. It just tells the app that it wants to insert some text and the app just handles that.

**Comment by johanneswilm** [comment]
ok, but first you need to split the text node to put the caret-element there, right? (given that you type in the middle of pre-existing text)

**Comment by rniwa** [comment]
Right. So I'd imagine there needs to be some event that signifies that the user wants to start typing some text at where the caret is currently located.

**Comment by johanneswilm** [comment]
Ok, then my two questions 2 and 3 still stand. They may sound quite specific, but I've run into trouble when trying to do collaborative writing when one user had two sibling text nodes where another just had one text node.

**Comment by rniwa** [comment]
I think the basic answer will be that (in my proposal), the browser doesn't do anything specific with regards to 2 and 3.  e.g. if the editor is serializing the edited content as HTML, then the HTML parser will create a single text node instead of two text nodes that are adjacent to each other since HTML isn't round trip safe for such a DOM tree.  Similarly, regardless of whether the app decides to insert text or not, the browser doesn't do anything with the caret element or the text nodes around it.

**Comment by johanneswilm** [comment]
> if the editor is serializing the edited content as HTML, then the HTML parser will create a single text node instead of two text nodes that are adjacent to each other since HTML isn't round trip safe for such a DOM tree.

True, but that's why normal HTML isn't a good enough format to store part of the DOM in when doing collaborative editing based on contenteditable=true. Instead we've had to create a script that serializes it to json so that sibling text nodes are preserved. See this open source project: https://github.com/fiduswriter/diffDOM

> Similarly, regardless of whether the app decides to insert text or not, the browser doesn't do anything with the caret element or the text nodes around it.

I think we need to be more specific. Else we will create problems for collaborative environments. Especially if browsers behave differently.

**Comment by johanneswilm** [comment]
I am looking a bit more into ShadowDOM. Would it not be possible, that when editing in a text node or elsewhere, at the start of the edit, to take the parentNode of the textnode that is to be edited, and to turn that into a shadow host. Then one copies exact copies of all the childNodes of the shadow host into the shadow root. One of these children will be the text node one wants to edit, so one goes ahead and edits that using IME or whatever. When the composition is done, the contents of the changed text node are compared with those of the old text node text node. Then the shadow root is destroyed and the insert intention event is triggered with the the text to be inserted as the argument?

**Comment by rniwa** [comment]
Sure, that'll work too.

**Comment by kojiishi** [comment]
I might be dreaming, but I wish the API spec abstracts details well enough so that browsers can choose whether it wants to use shadow DOM or other internal specially designed code.

API should describe what JS and browsers need to communicate to each other to accomplish IME handling. With that defined, one browser may choose to use shadow DOM as its internal implementation, while other browsers may use others. That'd be ideal for both JS and browser developers, right?

**Comment by johanneswilm** [comment]
@kojiishi @rniwa OK, so it sounds like we are closer to a solution?

@kojiishi Could you formulate it the way you are thinking? As I understand the need, it is basically to not update the DOM before finishing the character creation process and at the end of that to only trigger a text insertion intent that the JS takes care of? And then how exactly it achieves that is left up to the implementation, right?

**Comment by kojiishi** [comment]
I'm not suggesting anything concrete. For instance, whether to update DOM or not during the process is I think still controversial. I'm mildly leaning not to, but someone pointed out that then editors cannot auto-complete during the process. IIRC @rniwa and Ben wanted to appear in the DOM even during the process, but I need their confirmation for this. My concern was if we update, editors that are not aware of IME might not work well with IME. @rniwa and Ben were pretty confident that it was easy for editors to fix such issues, and updating DOM gives more flexibilities and features.

It'd be great if you could consolidate all such discussion points, and lead to a good resolution. I'm good whichever we resolve.

But the spec defining "use shadow DOM" looks a bit too much detail to me. If we resolve not to update DOM, that'd be enough details to assure interoperability for JS developers (I guess), browsers may use shadow DOM or not, but the spec should be written so that such decisions do not break interoperability.

Did I make myself clear? My English isn't great as you know, please ping me further if not.

**Comment by johanneswilm** [comment]
> I'm not suggesting anything concrete. For instance, whether to update DOM or not during the process is I think still controversial.

Ok, it sounded to me from the above that @rniwa had found something of a solutions

> My concern was if we update, editors that are not aware of IME might not work well with IME. @rniwa and Ben were pretty confident that it was easy for editors to fix such issues, and updating DOM gives more flexibilities and features.

Updating IME during the process I think will create a lot of problems for collaborative editors where one tries to keep two DOM trees in sync, or also editors that save the current state of the DOM as HTML no matter whether IME is currently in process or not. The nicest from the editors side would be if the DOM wouldn't be updated at all until the character is fully there, and then it just creates an intent. The second nicest would be if it just inserted one element during the process, the way @rniwa outlined above. Such an element shouldn't be two difficult to filter out when saving/sharing the document. Nevertheless, there are still issues with split text nodes, etc. that would need to be resolved.

**Comment by johanneswilm** [comment]
> But the spec defining "use shadow DOM" looks a bit too much detail to me. If we resolve not to update DOM, that'd be enough details to assure interoperability for JS developers (I guess), browsers may use shadow DOM or not, but the spec should be written so that such decisions do not break interoperability.

Sure, I can change the wording so that it doesn't mention the method explicitly, if that's fine with @rniwa as well.

> Did I make myself clear? My English isn't great as you know, please ping me further if not.

I think so. English isn't my first language either, and I'm still new to the language as it's used in these specifications. The most important is that it also makes sense to the browser people.

**Comment by johanneswilm** [comment]
> I'm not suggesting anything concrete. 

Right, but it would be good if we could get something concrete down in writing so we can move on. :)

So I will now wait for @rniwa and if he thinks it's OK to change the wording so that it simply says that the DOM doesn't change during the IME input process, then I'll do that,

**Comment by rniwa** [comment]
The idea here is to spec it in such a way that could be modeled as being implemented as a shadow DOM even though such will be an implementation detail.  The shadow DOM spec. will be defining something like user-defined shadow root so we should just use that concept instead of inventing our own exotic feature/concept.  In general, we're trying to construct/explain a higher level API (e.g. editing API) in terms of more primitive API (e.g. shadow DOM) instead of a higher level API introducing lots of primitives of its own.

**Comment by johanneswilm** [comment]
@rniwa I don't quite understand, these two sentences look a little contradictory to me:

> The idea here is to spec it in such a way that could be modeled as being implemented as a shadow DOM even though such will be an implementation detail. 

and

> The shadow DOM spec. will be defining something like user-defined shadow root so we should just use that concept instead of inventing our own exotic feature/concept.

Aren't you saying in one sentence that we should leave it up to the implementation how to achieve the goal, and in the second to use the terminology already defined in the shadow DOM spec?

> In general, we're trying to construct/explain a higher level API (e.g. editing API) in terms of more primitive API (e.g. shadow DOM) instead of a higher level API introducing lots of primitives of its own.

I understand the concept. I also understand the other concept of leaving certain details out so that the implementation can figure them out. But how do we do both at the same time?

**Comment by rniwa** [comment]
If we had used _closed shadow DOM_ then the fact we're using shadow DOM shouldn't be observable (to authors/JavaScript as well as end users). So for the purpose of writing the spec, we can just use concepts in shadow DOM and pretend it's implemented using shadow DOM. However, that doesn't mean that some browser vendor can't implement it in some other way.

For example, input[type=text] and textarea are implemented using shadow DOM with contenteditable in WebKit and Blink but such is not the case in some other engines. Nonetheless, all implementions more or less satisfy the API contract of input[type=text] and textarea.

I'm simply saying that the spec should refer to shadow DOM spec. for the sake of not defining its own shadow-DOM-like concept and features because there are many intricate details such as event retargeting, etc... that we could easily miss.  Just delegate the work to spec all that details to shadow DOM spec instead is all I'm saying.

**Comment by johanneswilm** [comment]
The wording now allows to use whatever mechanism is available in the browser. Shadow DOm is only mentioned as one possible way of implementing this.
