### ISSUE TITLE
Reference actions in clipboard API spec for execCommand copy/cut/paste

### ISSUE THREAD

**Issue by hallvors** [w3c/editing#61]
See discussion in https://github.com/w3c/clipboard-apis/issues/16 - in particular https://github.com/w3c/clipboard-apis/issues/16#issuecomment-125605131 and consider replacing the current text about copy/cut/paste in your execCommand spec with one saying you should invoke the actions as defined by my spec.

Thanks :)

**Comment by johanneswilm** [comment]
Ok. Agreed, if we keep execCommand, we should do that. Notice that it currently looks like we will decide to deprecate execCommand AND not spec it at the Paris F2F meeting. If this happens, the entire spec text will likely be removed and be replaced by a notice saying that execCommand is deprecated and will not be specced.

**Comment by hallvors** [comment]
If you drop execCommand(), how will JS trigger copy/cut/paste according to your spec?

**Comment by johanneswilm** [comment]
There will be an intent event for cut/paste, which you can find in the intent spec. At a later stage, there may be a higher level spec which includes handeling of those directly (without the use of JS). 

ContentEditable=True will likely also be deprecated and there will be decision not to spec it, the way it currently looks.

**Comment by johanneswilm** [comment]
@hallvors : sorry, for the earlier comment of mine. that was incorrect.

Right now there will only be intent events for all user actions and JS editor code then decides whether and how to react to that. The https://w3c.github.io/editing/input-events.html spec covers most of them, but for paste I think we could use the paste event triggered through https://w3c.github.io/clipboard-apis/#fire-a-clipboard-event , which JS then can use. At a later stage, there may be a higher level spec which includes handling of paste directly (without the use of JS). 

For cut, I wonder if this is just combining copy with a subsequent deleteContent intent. Any reason this wouldn't work?

ContentEditable=True will likely also be deprecated and there will likely be a decision not to spec it, the way it currently looks.

**Comment by johanneswilm** [comment]
@hallvors I have tried to incorporate the various points people made here in the issues to the editing specs. The execCommand spec draft has not changed as the only suggestion there really is for it to just be deprecated and the behavior not specified any further.

What we need for paste is a way to catch the users intent to paste certain text/html. We can add this to the input-events spec if it is not something you think should be in the clipboard-api.

For copy and cut, the main thing we need is a way to change the HTML/text that is being copied, and a way to preventDefault() the copying/cutting operation itself. The deletion that the cutting operation entails should be something the JS could should be able to handle itself. 

So for that we probably need either a JS function to add certain text/HTML as an entry to the clipboard, or a way to interrupt a copy operation and exchange the data that will be added to the clipboard. From what I can tell of the current spec draft, the copy action event should be enough for that. Any reason this wouldn't work?

I don't think we need a way to trigger copy/cut/paste from JS directly beyond that. Or at least I cannot imagine how to do that without causing a security issue by giving all JS universal access to the clipboard.

**Comment by hallvors** [comment]
"The user's intent" is like an event coming from the UA, right? I'm not sure if I understand how this might work. Let's simply go straight to a use case: AFAIK this group has several rich text editor developers. I'm pretty sure you'd all like to be able to put a "copy" button in a toolbar inside your editor and be able to control what goes on the OS clipboard when the user clicks that button. So: is this a use case you intend to handle, and if so how do you see it working?

**Comment by johanneswilm** [comment]
@hallvors Some of those who invented the concepts here have left the ship, but the rest of us are trying to build on what has been documented about these ideas. 

> "The user's intent" is like an event coming from the UA, right?

Yes, so basically copying will consist of at least two events: 
- The device dependent event: user hit CTRL+C.
- The device independent event: user wanted to copy the currently selected text.

One of the specs here defines the types of device independent events for most things, but not copy/paste/etc.

>  I'm pretty sure you'd all like to be able to put a "copy" button in a toolbar inside your editor and be able to control what goes on the OS clipboard when the user clicks that button.

In general, we have applied a much more limited approach to these "device independent events" than what had been thought of at previous stages. So these events will only be fired through doing right click menu actions, keydown combinations, etc. on the editable text itself. Other UI elements will not have access to creating similar intents, so normal function calls need to be used there.

> I'm pretty sure you'd all like to be able to put a "copy" button in a toolbar inside your editor and be able to control what goes on the OS clipboard when the user clicks that button. So: is this a use case you intend to handle, and if so how do you see it working?

I see the dilemma. I guess you don't want there to be a JS function to copy new content to the clipboard because this could represent a security issue by having random sites throw trash into the clipboard?

I tried doing just that with execCommand in current chrome, and there was apparently no security check preventing me from doing that: http://pastebin.com/fnVGa7wC

So unless you have a way to fix that in mind, I would say one has to choose between:
- Removing the option to copy by clicking on a custom UI button, due to security concerns.
- Not worrying about the security concerns and simply offering the functionality by means of a buitl in function.

What do you think?

**Comment by hallvors** [comment]
@johanneswilm see http://www.whatcouldbewrong.com/articles/html5-clipboard-support/ for a higher-level overview of how it's supposed to work now. This appears to have wide agreement among browser vendors (in fact implementations are underway in both Blink and Gecko), so it's considered safe enough. I'd also personally like to see some permission configuration that would allow sites to use _execCommand('paste')_, but I'm not holding my breath..

As you see, the solution for the "custom copy/cut/[paste] buttons" use case depends on document.execCommand(). If you're serious about "deprecating" it you may want to come up with an alternative way to do it.

(Now, I know that I haven't followed your discussions - and I've done enough QA on rich text editing functionality to know that it's complex - but it seems like this group simply concluded "the rich text editing stuff that browser vendors spent years and years developing and testing isn't good enough yet, so let's throw it away and make an API that lets JavaScript authors tackle all that complexity instead, because given yet another set of events to intercept will let them implement all the logic required for rich text editing in JS". Given the stunning amount of work Aryeh Gregor put into documenting what we've already got, the complexity of writing a good editor implementation and the fact browsers have spent so many years developing and testing already, this seems like an odd approach to me.)

**Comment by hallvors** [comment]
(Just to clarify: I'd assume that it's not possible to _remove_ a feature like contentEditable=true from the web platform due to the wide usage. IMO it's more likely that browser vendors will have to keep it in and give it some maintenance.. at that point adding another way to do similar things is mostly _adding_ complexity and confusion..)

**Comment by johanneswilm** [comment]
@hallvors To be sure, we started out as as some editor developers who simply wanted content editable fixed. It was the browser developers who communicated to us that this was an impossible task and the idea for this new approach was initiated on their side. We are merely trying to conclude the work they have initiated but didn't manage to finish. The claim of browser makers seems to be that there is so much broken legacy functionality in content editable so that it is unfixable. We who are working on the JS side of things just acknowledge that that is how browser vendors apparently see things.

**Comment by hallvors** [comment]
Oh well. IMHO they should think of the poor web developers and handle that pain themselves ;) but whatever.

Oh, and it's not an option to drop script-triggered copy - it's the most important request by far for the new spec. Google "ZeroClipboard" - everyone is using Flash for scripted copy-to-clipboard functionality now, and Flash is something we don't really want to rely on anymore for many obvious reasons..

**Comment by johanneswilm** [comment]
So if you or anyone else believes it is possible to convince the browser makers to change their mind AND you are able to get agreement among them to remove the brokenness from contenteditable/execCommand and make them behave in a consistent manner across browsers, then I really suggest for you guys to step forward and propose this plan. We are many who have been working for many years to have contentEditable fixed in one way or the other.

**Comment by johanneswilm** [comment]
@hallvors As for a practical proposal: Could we give access to the exact same execCommand copy/cut function just under a different function name for contentEditable=Intentions?

This should mean that it would have the same amount of security/insecurity as what you currently do with execCommand, and AFAIK it is rather unique in being the only functions for which we would need this from all of execCommand. Basically a "trigger copy/cut intent" function.

**Comment by johanneswilm** [comment]
@fredck I noticed that copying by clicking a custom button in the editor UI is something you guys also use in CkEditor. Do you guys have some preference about how to do this in cE=intentions?

**Comment by johanneswilm** [comment]
@hallvors btw, is Chrome working the way you expect it to? I noticed that Firefox would throw a security error in my example: http://pastebin.com/fnVGa7wC

If Chrome works the way you expect to, and the only thing that is important for you is that it is "user initiated", maybe such a user initiated check could simply be added to a normal function call that accepts the data to be added to the clipboard as an argument for use with cE=intentions?

If, on the other hand, Firefox is closer to the security level you are expecting, I think I would stick to my above proposal to simply have another function call instead of execCommand for use with cE=Intentions, so that browser makers eventually can remove execCommand altogether once they see usage has dropped to a very low number in a few years.

**Comment by hallvors** [comment]
Chrome handles that example fine, yes. Ignore Firefox, it will fall into line later ;)

**Comment by johanneswilm** [comment]
@hallvors How about this?
