### ISSUE TITLE
"CE Events Container" should be replaced by "editing host"

### ISSUE THREAD

**Issue by rniwa** [w3c/editing#66]
That's the term used in the old contenteditable and HTML5 specifications so we should be consistent with them.

**Comment by johanneswilm** [comment]
I see your point. 

I changed the name to "CE Events Editing Host". I didn't change the name outright to just "editing host" just yet because we need to be able to distinguish between an editing host with the events keyword set and those without in some way. 

"editing host" seems to be used mainly to describe the element which contains content that execCommand can manipulate. But a "CE Events Editing Host" is an exception to that in that there is no guarantee that it execCommand works on it.

There may be an even better wording.

**Comment by rniwa** [comment]
Can we not use capitalizations and acronyms like CE?  If anything, we should define "editing host type" instead of creating an entirely new concept especially since authors can mix the two.  For the purpose of writing a spec, I don't think we want two different terms.

**Comment by johanneswilm** [comment]
I am fine with not using capitalizations and acronyms if that is standard procedure. What do you mean by:

> authors can mix the two

?

**Comment by rniwa** [comment]
You can have contenteditable=events inside contenteditable=true. While such a configuration is unlikely to be useful, we need to define what happens.  Since we'll be talking about the closest anchor which is an editing host, etc... having to consider two different types of elements will complicate the spec text.

**Comment by johanneswilm** [comment]
> For the purpose of writing a spec, I don't think we want two different terms.

We need to distinguish between those editing hosts which can serve as editing hosts for execCommand and those that cannot serve as editing hosts for execCommand. The one in cE=true can serve as such an editing host, whereas those in cE=events cannot serve as such an editing host. At least we cannot guarantee that they do.

One solution A) would be to not use the term "editing host" for cE=events containers. Another solution B) would be to call them two different types of editing hosts. I am open to either one of those solutions or for an entirely different proposal

> You can have contenteditable=events inside contenteditable=true.

True. Given that the ultimate goal is to eliminate cE=true, I think the best is to keep the definition as simple as possible. Something like:

"Any element that has the contenteditable attribute set to `true` that is a descendant element of an element that has the contenteditable attribute set to `events` will be treated as if it its contenteditable attribute is not set."

And to cE=true add: 

"Any element that has the contenteditable attribute set to something else than `true` and `false` that is a descendant element of an element that has the contenteditable attribute set to `true` will be treated as if it its contenteditable attribute is not set."

Just one example. I don't really care for how to handle that case, as long as the definition is simple and not open to ambivalence.

@rniwa Would adding that text be useful in your view? Or do you ave an alternative suggestion?

**Comment by rniwa** [comment]
> We need to distinguish between those editing hosts which can serve as editing hosts for execCommand and those that cannot serve as editing hosts for execCommand. The one in cE=true can serve as such an editing host, whereas those in cE=events cannot serve as such an editing host. At least we cannot guarantee that they do.

Right.

> One solution A) would be to not use the term "editing host" for cE=events containers. Another solution B) would be to call them two different types of editing hosts. I am open to either one of those solutions or for an entirely different proposal

I'd prefer B to avoid introducing two made-up terms that refer to very similar things.

> True. Given that the ultimate goal is to eliminate cE=true, I think the best is to keep the definition as simple as possible. Something like

I don't think we necessary want to eliminate `contenteditable=true`.  We're adding `contenteditable=events` now because spec'ing the former is really hard, and we can't easily reach an interoperability but we should aim to eventually reach interoperability between browsers.  In a way, you could think of `contenteditable=events` as "desugaring" `contenteditable=true`.  In that case, spec'ing `contenteditable=events` and adding more primitives should help browser engines to slowly converge to an interoperable implementing of `contenteditable=true` over time (like in 10-20 years).

**Comment by johanneswilm** [comment]
> I don't think we necessary want to eliminate `contenteditable=true`.  We're adding `contenteditable=events` now because spec'ing the former is really hard, and we can't easily reach an interoperability but we should aim to eventually reach interoperability between browsers.  In a way, you could think of `contenteditable=events` as "desugaring" `contenteditable=true`.  In that case, spec'ing `contenteditable=events` and adding more primitives should help browser engines to slowly converge to an interoperable implementing of `contenteditable=true` over time (like in 10-20 years).

Yeah, that is a possibility. I think what we all agree on is that we want to have a way to turn events and possibly later modules (clipboard, typing enter caret, etc.) modes on all at the same time, no matter whether the term is "true" or "all" or whatever it will be. Effectively that should correspond more or less to all the functionality that cE=true has now, jsut more standardized and bug-free-er.

As for whether cE=true itself can be fixed or not -- the various browser people, such as you, have given different explanations. Some say it cannot be changed because too much content is relying on today's broken implementations and that some websites will never update and therefore it can never change. Others say it can and should be standardized. So it's hard to know what is the case.

Sitll, unless you see a reason for it, I would think it would be the most simple to try to just make it impossible to nest the two contenteditable types inside of oneanother, both because that is easier to define, and I would imagine also less cause for weird browser bugs. Or what do you have in mind?

**Comment by rniwa** [comment]
Preventing the nesting of different types of `contenteditable` is considerably harder to implement correctly in browsers so I'd rather not do that.

**Comment by rniwa** [comment]
Anyway, if we have modules such as clipboard, typing enter caret, etc... we certainly don't want to define a different element type for each one of them so I think we should stick with "editing host" and defining the type or the list of active modules as a concept.

**Comment by johanneswilm** [comment]
> Anyway, if we have modules such as clipboard, typing enter caret, etc... we certainly don't want to define a different element type for each one of them

No, certainly not. The nesting prevention would just be for the old cE=true. But if you say it's no problem figuring that out... well, then we don't need to touch that.

>  so I think we should stick with "editing host" and defining the type or the list of active modules as a concept.

Yes, I changed the wording now so it doesn't try to redefine it entirely and just talks about a specific type of editing host. Do you think this wording will work?

**Comment by johanneswilm** [comment]
Done
