### ISSUE TITLE
Definition of "Invisible elements" is vague

### ISSUE THREAD

**Issue by rniwa** [w3c/editing#68]
The current definition:

> All elements that after the application of CSS are invisible, either due to CSS properties or because the type of element would not have been rendered even without CSS.

is too vague. For example, does an element with `visibility: hidden` considered as invisible for this purpose?  How about `visibility: collapse`.  We need a precise definition for this.

**Comment by johanneswilm** [comment]
Right. Should we just create a list of every type of element we consider to be invisible maybe? Some things are invisible already before applying CSS (such as comment nodes), whereas others are invisible after applying CSS (such as when display:none; is applied).

**Comment by kojiishi** [comment]
> Should we just create a list of every type of element we consider to be invisible maybe?

Yes, a clear definition would help. e.g., should we include elements with height=0, empty spans, opacity:0, lower z-index, overflow, ...there are too many invisible elements in CSS.

**Comment by rniwa** [comment]
@kojiishi : would you be able to create such a list since you're probably most knowledgable in this area?

**Comment by kojiishi** [comment]
I actually prefer as least rules hardcoded in UA as possible -- ideally none, if it's acceptable by JS developers. That way, JS frameworks can catch up new CSS constructs without going through the standardization process.

@johanneswilm, what do you think?

**Comment by johanneswilm** [comment]
The initial point with making a list of points where it needs to be possible to put the caret and for it to also render, was to avoid the situations that currently exist where one needs to insert empty space characters or alike in JS in order to be able to put the caret in certain spaces. Checkout this example: https://bug873883.bmoattachments.org/attachment.cgi?id=751510 All browsers have problems with putting the caret in some places there, but they differ. Some places they seem to want to put the caret, just not draw it, in order places it cannot go at all.

So if the same objective can be achieved in another way, then I'm also fine with that.

**Comment by johanneswilm** [comment]
The initial point with making a list of points where it needs to be possible to put the caret and for it to also render, was to avoid the situations that currently exist where one needs to insert empty space characters or alike in JS in order to be able to put the caret in certain spaces. Checkout this example: https://bug873883.bmoattachments.org/attachment.cgi?id=751510 All browsers have problems with putting the caret in some places there, but they differ. Some places they seem to want to put the caret, just not draw it, in order places it cannot go at all.

@kojiishi So if the same objective can be achieved in another way, then I'm also fine with that.

**Comment by johanneswilm** [comment]
s for whether or not a "vague" description of "invisible elements" is good enough or not is something you browser people will have to decide, @kojiishi @rniwa .

**Comment by kojiishi** [comment]
> As for whether or not a "vague" description of "invisible elements" is good enough or not is something you browser people will have to decide,

I prefer either to remove it, or make it more complete.

> All browsers have problems with putting the caret in some places there, but they differ.

I'm sorry for the current situation, but let's forget this for now. At least in CE=events (and hopefully more if backward compat is ok) UA sets the caret to anywhere JS specifies.

In that world, however, JS must be responsible for either 1) not to set carets where it's not visible or not possible to type, or 2) tweak DOM so that carets are visible and typing is possible.

I prefer that, but if JS developers prefer UA doing more and automatically avoid setting selections to "invisible elements", I agree with @rniwa that the definition needs to be more complete.

So, remove or have a list, which do you prefer?

**Comment by johanneswilm** [comment]
> I'm sorry for the current situation, but let's forget this for now. At least in CE=events (and hopefully more if backward compat is ok) UA sets the caret to anywhere JS specifies.

Ok, not really knowing what's going on in a browser, it's not really clear to me why the caret will be drawn correctly every time with the new code, without us specifying anything about that in the spec. In the old code, it seems that there are certain places where the caret line is being drawn somewhere slightly different, and it doesn't blink while it's there. That's one of the kinds of things we want to avoid. The second, as you mention, that the caret/selection will not let itself be placed in certain places.

So the second is solved, but the first one? For that, I thought it would be the simplest to give you a list of places where the caret needs to be drawable (incl. blinking), but if say that doesn't help you, then we can remove it as well. How can we then ensure that if a specific browser does what Chrome does with the current setup, that we can file a bug because it doesn't draw the caret when it should?

I am fine with JS being responsible for not putting carets where they aren't visible and tweaking the DOM if necessary to make them visible.

**Comment by johanneswilm** [comment]
@kojiishi So given these circumstances, does that mean that you would be in favor of making the list more specific? Would you be willing to make that list?

**Comment by kojiishi** [comment]
The canonicalization, in Blink/WebKit terminology, is a concept to try to move carets to a _sane_ place. For instance, when user/JS pressed "right", and there's a `<div style="display:none"></div>` next to the caret, it makes sense to skip it.

There are several such rules to make it saner and better, built in years. However, since those rules were defined in an ad-hoc manner and were never spec'ed, when all rules were combined against a specific DOM tree, rules conflict to each other and the logic is lost to where it should move carets to. That is what you're seeing when JS cannot set selections to. I'm not familiar with cases where the caret does not blink, but I guess the same cause.

That is why we're hesitant to fix specific bugs today. By adding another ad-hoc rule, we'll make the rules more complicated, and probably introduce yet another case where we cannot set selections to. Take an example of [crbug.com/456917](http://crbug.com/456917). Our first idea to fix it was to synthesize the height for the empty `<p>`, but then figured out that such behavior is not interoperable with Gecko/Trident. Our next idea was to allow setting selections to height=0 just like Gecko/Trident does in this case, but we're not sure if that's really what Gecko/Trident does, and since the rule was baked in Blink/WebKit for a long period, we're not sure how much it can break.

I think we share a goal that, clearly defined, simple, and non-contradicting rules in the spec are desired. With that, we can really fix bugs. Ideally I'd like Gecko and Trident to join the discussions too (maybe it's time to ping Trident folks again?), but at least when a stable spec approaches to CR or such milestones, we can expect them to review the spec and object if any.

When you file bugs against browsers, if the bug has a link to a stable spec, it's obvious that the bug is not talking about only one specific case and is not likely to introduce other edge cases. Browser developers are clear how to fix, and should feel easier to take the fix.

Does this make sense, how the specing would help fixing bugs you want browser developers to fix, possibly including Gecko/Trident?

**Comment by kojiishi** [comment]
> So given these circumstances, does that mean that you would be in favor of making the list more specific? Would you be willing to make that list?

After some thoughts, my proposal would be to define as `display: none` only. Other _invisible elements_ are to be handled by JS, possibly with help from some other rules, such as ones to be defined in #70.

The motivation is that when `display: none`, CSS defines that UA should not generate boxes. That makes browser developers a little hard to handle such elements the same way as other elements.

As originally pointed out, there are other _invisible elements_ that, from user perspective, should be skipped, but if JS can handle them, that looks ideal to me.

What do you think?

**Comment by johanneswilm** [comment]
> After some thoughts, my proposal would be to define as display: none only. Other invisible elements are to be handled by JS, possibly with help from some other rules, such as ones to be defined in #70.

How about comment nodes and possibly other nodes that do not generate boxes even before applying CSS?

> The canonicalization, in Blink/WebKit terminology, is a concept to try to move carets to a sane place. For instance, when user/JS pressed "right", and there's a <div style="display:none"></div> next to the caret, it makes sense to skip it.

All of this makes sense. Question then: Does this mean, that if we allow for movement of the caret by default with all these "canonicalization" rules turned off, and one adds no extra JS library for caret movement, the caret is bound to disappear into places where it cannot be displayed every now and then, and it will then not reappear either by hitting the same key more times? (for example, hitting the down key 50 times until the caret is somewhere that it previously would have been moved away from based on "canonilicazation" rules)

If this is the case, then I wonder if it really is a good idea to keep caret movement by the browser enabled by default. It would seem like somewhat of a useless feature, if one needs to reimplement it in JS anyway.

**Comment by johanneswilm** [comment]
> After some thoughts, my proposal would be to define as display: none only. Other invisible elements are to be handled by JS, possibly with help from some other rules, such as ones to be defined in #70.

I don't really have any issues with it. If comment nodes and display:none nodes are handled completely different by browsers and one can be handled fine by JS, whereas the other one cannot, then that's totally fine and we'll just specify `display:none` here.

**Comment by johanneswilm** [comment]
> Ideally I'd like Gecko and Trident to join the discussions too (maybe it's time to ping Trident folks again?), but at least when a stable spec approaches to CR or such milestones, we can expect them to review the spec and object if any.

Agreed. I have tried to contact absolutely everyone in this space, and last I spoke to some Trident people (in May/June) they said someone would eventually join this effort again. Luckily Benjamin was able to collect a lot of input from Microsoft internal projects before he left, so hopefully that means we already are covering a lot of their needs. The F2F may be another forum to figure out who else should get involved in these discussions.

**Comment by gked** [comment]
Hey guys,
this is Grisha, I am new Trident person. 
Sorry, I wasn't involved in your discussions too much as I was in the process of ramping up at the new place. Sure thing, I am willing to help with whatever needs to be done on Edge side. Once there is an agreement on the definition, I can have the spec reviewed.

**Comment by johanneswilm** [comment]
@kojiishi I have now made clear that "element" are just element nodes and added your preferred way of defining invisible elements. I will close this issue at this time.

**Comment by rniwa** [comment]
I don't think the following text is precise enough for a spec:

> All element nodes that have `display:none` set through CSS.

In particular, "set through CSS" needs to be replaced by something more precise.  e.g. the used value of `display` property resolves to the value `none`.
