### ISSUE TITLE
InputEvent.targetRange in <input>

### ISSUE THREAD

**Issue by masayuki-nakano** [w3c/editing#72]
> targetRange of type Range, readonly
> 
>  the Range in the document that is affected by this event. Typically the primary Range on the document's Selection.

I think that the selection range in <input> cannot be represented with DOM Range. So, when an input event is fired on <input>, what's the expected value of this attribute?

**Comment by spocke** [comment]
Good point since if a new beforeinput event is introduced one expect it to work on all input elements not just contentEditable. So some new type of struct holding selectionStart/selectionEnd needs to set as the targetRange or in a separate property since it might be confusing to call it range when it's more of a textrange but that might be confused with the old IE TextRange.

**Comment by johanneswilm** [comment]
What's the usecase for using this in <input type=text> elements?

**Comment by johanneswilm** [comment]
for <input> there is the change event, which AFAIK is not available for cE on any browser. Is there any reason one would want/need the beforeinput event instead of the onchange events on input fields?

**Comment by spocke** [comment]
The problem is that input event fires on input/textarea/cE so it would be confusing not supporting textareas for beforeinput since they basically have the same name. Also people might want to have similar control over the selection in a textarea checking for composition, caret movement etc. If beforeinput only fires on cE elements then maybe it should be called something else.

I as an editor implementor wouldn't need it but we need to think broader than just rich text here if we are to introduce new global events.

**Comment by johanneswilm** [comment]
I can see your point about the name, and currently it's also specced to work on <input> fields. But unless this is something really needed to work effectively with textareas/input fields, I would say this isn't really needed.

> If beforeinput only fires on cE elements then maybe it should be called something else.

Possibly yes. Currently there is the `input` event for both cE and relevant <input> elements, `change` which only works on <input>-elements, and now we would add this new event which only works on elements that can contain a normal DOM-range selection (so not <input>-elements). I would almost think it would be more confusing if this event would sometimes throw out one type of range and sometimes a different, and AFAIK there hasn't been the same cry for improvement in the <input type=text> community as there has been in the cE-community, AFAIK, so unless we can find a usecase where this is really important to have, I think I would advocate for either removing it from <input> elements AND possibly change the name of it.

**Comment by spocke** [comment]
Sure. So the targetRange could be set to where the DOM Range currently is as specified in the current Input Events specification by the line "Typically the primary Range on the document's Selection." but is that to vague.

In Chrome getting a DOM Range when being inside a textarea results in.
range.setStartAfter(textarea);
range.setEndAfter(textarea);

However IE doesn't return any range when being inside a textarea.

**Comment by Reinmar** [comment]
I understand that there may be some confusion if we introduce `beforeinput` that would work only in cE elements, but nothing stands in a way of adding it later for inputs and textarea. So I would add it now only for cE elements. The current name is IMO fine.
