### ISSUE TITLE
move all caret movement intention events from beforeinput to beforeselectionchange?

### ISSUE THREAD

**Issue by johanneswilm** [w3c/editing#73]
beforeselectionchange has been mentioned a few times. This event should be in the Selection API. If the caret movements intentions are to be moved there, it's important that the beforeselectionchange event contains the user intention (such as: "caret up"). 

Alternatively the beforeselectionchange event can just have a from-range and a to-range that doesn't need to specify what user intention caused the selection change, and we keep the intended caret movement events the beforeinput.

**Comment by Reinmar** [comment]
Yes, that's how I would see it too. Then we would have a cleaner `beforeInput` event which would be really only about the "input". And a separate `beforeSelectionChange` event which would about selection.

**Comment by spocke** [comment]
Yes. Makes more sense to have that in the Selection API spec.

**Comment by johanneswilm** [comment]
@rniwa What do you think? Would the beforeselectionchange event as you imagine it contain the user intention?

**Comment by Reinmar** [comment]
I created https://github.com/w3c/selection-api/issues/56 for the Selection API spec.

**Comment by johanneswilm** [comment]
F2F has decided to change the names of the events to beforeEdit and Edit and only have them apply to contenteditable elements.

**Comment by ojanvafai** [comment]
Which events were renamed to beforeEdit/Edit?

**Comment by johanneswilm** [comment]
@ojanvafai The ones that were called beforeInput/Input. The reason was that we already have an "Input" event which works on input elements, textareas and contenteditable, but gives no good information. We wanted to make clear that this does not apply to <input> fields, which the Input event DOES apply to.

About half of the editTypes we then moved to beforeselectionchange -- all the ones related to moving the caret somewhere or selection things (selecctAll, etc.)

**Comment by ojanvafai** [comment]
Moving the caret movement types to beforeselectionchange makes sense to me. That seems orthogonal to renaming the event though.

I don't think the renaming makes sense. As you say, we already have an input event. If we rename these, then every input will end up having to fire beforeEdit, edit _and_ input in addition to whatever keyboard events need to fire. This is bad for performance and bad for authors (one more event type they need to learn). 

Also, Blink/WebKit implement <input> as a wrapper around contentEditable. IMO, that's a good thing and it's one that we should build on and encourage all browsers to move to. Conceptually, the end result should be that <input> is a shadow DOM wrapper around a contentEditable=events element.

I wasn't there on the second day of the F2F when this was discussed, but as I understand it the concerns are:
1. We don't want to issue beforeInput/input events with a "bold" editType on <input>
2. targetRange doesn't work on <input>.

I agree with those concerns, but would be happier solving them in a different way. The beforeInput/input events just shouldn't fire for <input> if the user hits ctrl+b, etc and targetRange should be null.

This fits into the platform layering model of <input> being a wrapper around contentEditable because conceptually:
1. The code that dispatches beforeInput/input for ctrl+b would be a feature of the code that implements contentEditable=typing on top of contentEditable=events 
2. The code that fills targetRange would know to leave it out for closed shadow roots (once we finally get those specced and implemented).

**Comment by johanneswilm** [comment]
True, those were the concerns. Additionally, we found the Input-field had some other fields in some UAs and none in other UAs. 

Discussion has been moved to new issue #87

**Comment by johanneswilm** [comment]
Some more things I discovered: 

* The beforeInput event is actually mentioned in several other specs. For example here: https://w3c.github.io/uievents/#h-sync-async or https://w3c.github.io/uievents/#h-events-keyboard-event-order but with a broken link. It is described as synchronous (correctly) and I also think ti describes correctly the order of events.
* At above links the beforeInput event is described as "only for keys which produce a character value". I don't think that corresponds to how we want to use that event with formatting bold, etc..
* Here it describes the InputEvent: https://developer.mozilla.org/en-US/docs/Web/API/InputEvent but the link to the specification gives us another dead link. I can see that the event was removed from that spec in January: https://github.com/w3c/uievents/commit/b2bd0cfea66b00a0fc7f25993716a3374db90beb due to a bug report by Gary Kacmarcik (Google) https://lists.w3.org/Archives/Public/www-dom/2015JanMar/0029.html


.... so altogether it seems as if the beforeInput/Input events mentioned other places are earlier versions of the event we have been describing in this spec until it changed name due to the decisions of the F2F.

Testing it out on Chrome and FF, it doesn't look like the input event on cE=true elements holds any information.
